version: 2.1
orbs:
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.2.3


# jobs:
  # build-and-test:  
  #   docker:
  #     - image: cimg/python:3.10.5
    
  #   steps:
  #     - checkout
  #     - python/install-packages:
  #         pkg-manager: pip
  #         # app-dir: ~/HITBACKSUCIDE  # If you're requirements.txt isn't in the root directory.
  #         # pip-dependency-file: requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
  #     - run:
  #         name: Run tests
  #         command: pytest

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pip install pytest
      - run:
          name: Run snscrape
          command: pip install snscrape
      - run:
          name: Run spacy
          command: pip install spacy       
      - run:
          name: Run vs
          command: pip install vaderSentiment
      - run:
          name: Run flask
          command: pip install flask       
      - run:
          name: Run wc
          command: pip install wordcloud 



  build-and-test-angular:
    working_directory: ~/ng-project
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - run: 
          command: cd angular-HitBack &&npm install
      - run: 
          command: cd angular-HitBack && npm run test
        

workflows:
  sample:
    jobs:
      - build_and_test
      #- build-and-test-python-requirements
      #- build-and-test-python-test-cases
      - build-and-test-angular
